name: Fetch Telegram Channel Posts

on:
  schedule:
    - cron: '0 */2 * * *'  # هر ۲ ساعت اجرا میشه
  workflow_dispatch:

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    env:
      YOUR_BOT_TOKEN: ${{ secrets.YOUR_BOT_TOKEN }}
      CHANNEL_USERNAME: YourChannelUsername  # اسم یوزرنیم کانالت (بدون @)

    steps:
    - uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Fetch channel posts from Telegram
      run: |
        echo "Fetching channel posts..."

        # گرفتن پیام‌های کانال (channel_post)
        curl -s "https://api.telegram.org/bot${YOUR_BOT_TOKEN}/getUpdates?allowed_updates=channel_post&limit=10" > posts.json

        echo "API Response:"
        cat posts.json

        # استخراج دو پست آخر
        jq '[.result[] | select(.channel_post != null) | .channel_post | {
          text: (.text // .caption // "بدون محتوا"),
          date: .date,
          link: "https://t.me/'"${{ env.CHANNEL_USERNAME }}"'"
        }] | reverse | .[:2]' posts.json > posts_formatted.json || echo "jq failed or no channel_post found"

    - name: Generate telegram-posts.html
      run: |
        echo '<div class="telegram-posts">' > telegram-posts.html
        jq -r '.[] | "<div class=\"telegram-post\"><a href=\"" + .link + "\" target=\"_blank\" class=\"post-link\">" + .text + "</a><br><small>" + (.date | todate) + "</small></div>"' posts_formatted.json >> telegram-posts.html
        echo '</div>' >> telegram-posts.html

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add telegram-posts.html
        git commit -m "Update Telegram channel posts" || echo "No changes to commit"
        git push
