name: Update Telegram Posts

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت اجرا میشه
  workflow_dispatch:     # امکان اجرای دستی

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon

      - name: Run script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        run: |
          python telegram_script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'sinavm'
          git config --global user.email 'sinabb.2006@gmail.com'
          git add telegram-posts.html posts_formatted.json
          git commit -m "Update Telegram posts" || echo "No changes to commit"
          git push
