name: Update Telegram Posts

on:
  schedule:
    - cron: '0 */2 * * *'  # اجرا هر دو ساعت در دقیقه صفر
  workflow_dispatch:     # امکان اجرای دستی

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon
          pip list

      - name: Create post-channels directory
        run: |
          mkdir -p post-channels
          echo "post-channels directory created or already exists"

      - name: Check files before running scripts
        run: |
          ls -la
          echo "Checking if telegram_script.py exists"
          test -f telegram_script.py && echo "telegram_script.py found" || echo "telegram_script.py not found"
          echo "Checking if channels_script.py exists"
          test -f post-channels/channels_script.py && echo "channels_script.py found" || echo "channels_script.py not found"

      - name: Run telegram_script.py
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "Starting telegram_script.py execution..."
          python telegram_script.py 2>&1 | tee script_output.log
          echo "telegram_script.py execution finished."
          cat script_output.log

      - name: Run channels_script.py
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "Starting channels_script.py execution..."
          python post-channels/channels_script.py 2>&1 | tee post-channels/script_output.log
          echo "channels_script.py execution finished."
          cat post-channels/script_output.log
        continue-on-error: true  # ادامه دادن حتی در صورت خطا

      - name: Check files after running scripts
        run: |
          ls -la telegram-posts.html posts_formatted.json || echo "Main channel output files not found"
          ls -la post-channels/posts_formatted.json post-channels/config.json post-channels/telegram_proxy.json || echo "Channels output files not found"

      - name: Commit and push changes
        run: |
          git config --global user.name 'sinavm'
          git config --global user.email 'sinabb.2006@gmail.com'
          git add telegram-posts.html posts_formatted.json
          git add post-channels/posts_formatted.json post-channels/config.json post-channels/telegram_proxy.json
          git commit -m "Update Telegram posts and channels configs/proxies" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push
