name: Fetch Telegram Posts

on:
  schedule:
    - cron: '0 */2 * * *' # هر ۲ ساعت اجرا میشه
  push: # برای اجرای دستی

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    env:
      YOUR_BOT_TOKEN: ${{ secrets.YOUR_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PROXY: http://YOUR_PROXY_IP:PORT  # اینجا پروکسی رایگان یا خودت رو بذار

    steps:
      - uses: actions/checkout@v4

      - name: نصب jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: دریافت پست‌ها از تلگرام با پروکسی
        run: |
          echo "Fetching Telegram posts using proxy $PROXY"
          curl -x $PROXY -s "https://api.telegram.org/bot${YOUR_BOT_TOKEN}/getUpdates?limit=5" > posts.json
          echo "API Response:"
          cat posts.json

          jq '[.result[] 
            | select(.message.chat.id == (env.TELEGRAM_CHAT_ID | tonumber)) 
            | .message 
            | {
                text: (.text // .caption // "بدون محتوا"),
                date: .date,
                link: ("https://t.me/" + (.chat.username // ""))
              }
          ] | reverse | .[:2]' posts.json > posts_formatted.json

      - name: ساخت فایل HTML پست‌ها
        run: |
          echo '<div class="telegram-posts">' > telegram-posts.html
          jq -r '.[] | "<div class=\"telegram-post\"><a href=\"" + .link + "\" target=\"_blank\" class=\"post-link\">" + .text + "</a><span class=\"post-date\">" + (.date | todate) + "</span></div>"' posts_formatted.json >> telegram-posts.html
          echo '</div>' >> telegram-posts.html

      - name: ذخیره تغییرات
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add telegram-posts.html
          git commit -m 'Update Telegram posts' || echo "No changes to commit"
          git push
